name: Scheduled Workflow

on:
  # schedule:
  #   - cron: '45 10 * * *'
  workflow_dispatch:
jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print UTC date
        run: date
      - name: Print local date
        run: |
            TZ='Asia/Shanghai' date  
            echo "version=$(date +'%Y-%m-%d %H:%M:%S')" >>$GITHUB_ENV
      - name: Send email
        uses: bgvioletsky/send_email@v1.0.0  # 替换为你的仓库信息
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 书香门第签到
          body: ${{ env.version }}
          to: ${{ secrets.AIM_EMAIL }}
          from: ${{ secrets.EMAIL_USERNAME }}
          html: false
              