name: Daily Scheduled Workflow

on:
  schedule:
    - cron: '30 3 * * *'  # 每天的 03:30 UTC，即 11:30 CST

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run a script
        run: echo "This job runs every day at 11:30 AM CST."